create table if not exists predictions (
  id bigint generated by default as identity primary key,
  symbol text not null,
  timeframe text not null,
  generated_at timestamptz,
  direction text,
  trade_recommendation text,
  bullish_probability numeric,
  bearish_probability numeric,
  confidence numeric,
  risk_level text,
  signal_grade text,
  payload jsonb,
  created_at timestamptz default now()
);

create table if not exists market_candles (
  symbol text not null,
  timeframe text not null,
  time bigint not null,
  open numeric not null,
  high numeric not null,
  low numeric not null,
  close numeric not null,
  volume numeric default 0,
  primary key (symbol, timeframe, time)
);

create table if not exists trade_journal (
  id uuid primary key,
  symbol text,
  direction text,
  entry numeric,
  exit numeric,
  result numeric,
  notes text,
  created_at timestamptz default now()
);

create table if not exists backtests (
  id uuid primary key,
  symbol text,
  timeframe text,
  trades int,
  win_rate numeric,
  profit_factor numeric,
  drawdown numeric,
  accuracy numeric,
  created_at timestamptz default now()
);
