export enum MarsEventTypes {
  OBSERVATION_CREATED = 'OBSERVATION_CREATED',
  RESEARCH_TRIGGERED = 'RESEARCH_TRIGGERED',
  EXPERIMENT_STARTED = 'EXPERIMENT_STARTED',
  HYPOTHESIS_GENERATED = 'HYPOTHESIS_GENERATED',
  EVIDENCE_COLLECTED = 'EVIDENCE_COLLECTED',
  EXPERIMENT_RESOLVED = 'EXPERIMENT_RESOLVED',
  KNOWLEDGE_UPDATED = 'KNOWLEDGE_UPDATED'
}

export interface MarsEvent<T = any> {
  type: MarsEventTypes;
  payload: T;
  timestamp: number;
}
