import { CalibrationConfigManager } from './CalibrationConfigManager';
import { CalibrationDatasetValidator, HistoricalRecord } from './CalibrationDatasetValidator';
import { HistoricalEvaluator } from './HistoricalEvaluator';
import { ParameterOptimizer } from './ParameterOptimizer';
import { CalibrationReporter, CalibrationReport } from './CalibrationReporter';
import { LoggerService } from '../../../LoggerService';
import * as fs from 'fs';
import * as path from 'path';
import { app } from 'electron';

export class CalibrationFramework {
  public configManager: CalibrationConfigManager;
  private datasetValidator: CalibrationDatasetValidator;
  private evaluator: HistoricalEvaluator;
  private optimizer: ParameterOptimizer;
  private reporter: CalibrationReporter;

  constructor(customPath?: string) {
    this.configManager = new CalibrationConfigManager(customPath);
    this.datasetValidator = new CalibrationDatasetValidator();
    this.evaluator = new HistoricalEvaluator();
    this.optimizer = new ParameterOptimizer(this.evaluator);
    this.reporter = new CalibrationReporter();
  }

  /**
   * Main entry point to run calibration. 
   * NEVER modifies production automatically. Only produces a candidate.
   */
  public runCalibrationSession(dataset: HistoricalRecord[]): CalibrationReport | null {
    LoggerService.info('[CalibrationFramework] Initiating calibration session...');

    // 1. Validate Dataset
    const validation = this.datasetValidator.validate(dataset);
    if (!validation.isValid) {
      LoggerService.error('[CalibrationFramework] Calibration aborted due to dataset validation failure.');
      return null;
    }

    // 2. Get Active Production Profile
    const activeProfile = this.configManager.getActiveProfile();

    // 3. Shadow Mode / Baseline Evaluation
    // We evaluate the active profile on the dataset to get a baseline
    const baselineMetrics = this.evaluator.evaluate(dataset, activeProfile);
    this.configManager.logAudit({
      timestamp: Date.now(),
      action: 'SHADOW_MODE_RUN',
      targetProfileId: activeProfile.id,
      reason: 'Baseline evaluation before optimization',
      metricsAfter: baselineMetrics
    });

    // 4. Generate Candidate Profile (Optimization)
    const candidateProfile = this.optimizer.generateCandidate(activeProfile, dataset);
    
    // 5. Walk-Forward Validation on Candidate
    const candidateMetrics = this.evaluator.walkForwardValidate(dataset, candidateProfile, 0.7);

    // 6. Save Candidate
    this.configManager.saveCandidateProfile(candidateProfile, 'Generated by automated calibration session');

    // 7. Generate Report
    const report = this.reporter.generateReport(activeProfile, baselineMetrics, candidateProfile, candidateMetrics);
    
    // Save report to disk for external review
    this.saveReportToDisk(report);

    LoggerService.info('[CalibrationFramework] Calibration session complete. Awaiting manual approval.');
    return report;
  }

  private saveReportToDisk(report: CalibrationReport): void {
    try {
      const userDataPath = app?.getPath('userData') || process.cwd();
      const reportPath = path.join(userDataPath, `calibration_report_${report.candidateProfileId}.md`);
      fs.writeFileSync(reportPath, report.reportMarkdown, 'utf-8');
      LoggerService.info(`[CalibrationFramework] Saved report to ${reportPath}`);
    } catch (err) {
      LoggerService.error(`[CalibrationFramework] Failed to save report: ${err}`);
    }
  }

  /**
   * Explicitly activates a candidate profile. This is the ONLY way production changes.
   */
  public approveAndActivateCandidate(candidateId: string): boolean {
    LoggerService.info(`[CalibrationFramework] Manual approval received for ${candidateId}`);
    return this.configManager.activateProfile(candidateId, 'Explicit manual approval by user/admin');
  }

  /**
   * Rolls back to a previous known profile.
   */
  public rollback(profileId: string): boolean {
    return this.configManager.rollbackToProfile(profileId, 'Emergency manual rollback');
  }
}
